//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDTag
    {
        public System.Guid ID { get; set; }
        public string RFIDUID { get; set; }
        public string TagName { get; set; }
        public string TagType { get; set; }
    }
}
